project:
  type: website

website:
  title: "Home Energy Imrovements project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: com.gmd
        text: Com
      
      
      #- sidebar:More

  ##sidebar: 
    #  - id: ""
    #  - id: More
    #  title: "More"
    #  style: "docked"
      #collapse-level: 2
      #contents:
       # - com.gmd
#

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

